### ISSUE TITLE
Accumulate Errors/Exceptions 

### ISSUE THREAD

**Issue by edvaldo3v** [acidiney/node-dto#22]
when i pass 2 invalid field it throw exception with first error, but i think it should throw all error or exception accumulated

**Comment by acidiney** [comment]
In version 2.0.0, was introduced validateAsync, it does not throws, instead returns the result of validation.Eg: 
```ts
import { MakeDto, TYPES } from 'node-dto';

(function () {
  const schema = MakeDto([{
    name: 'Username',
    serialize: 'username',
    required: true,
    type: TYPES.NUMBER
  }])

  console.log(schema.validateAsync({ Username: 'test' }))
})()

// Result

// { success: false, errors: [ { username: 'INVALID_NUMBER_ERROR' } ] }
```

> Please note that if you use `.validate` it will throws as normally
